# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 872478b77a2494f2e1c4eeb1eae23a8759a7103548c4b74a28a4af3a7ebfc5084ce706da3c575c2b071e6e2d28c0ed13749ecf94d79f7c2c6573d2d28026cd21

test:
  secret_key_base: 8820db494820c861c48aadd38da5190824b96ac603ca740aa59276086ebab426a1e7a67979cc897091d4086d1fdde047ddb9008529318b4ff8e40dac7e6954cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
